version: "3.8"
services:
  production:
    container_name: fohormohor_fe_production
    image: fohormohor_fe_production
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:80"
    restart: unless-stopped
