export const NAVIGATION_ROUTES = {
  BASE: "/",
  ABOUT_US: "/about-us",
  WHAT_WE_BUY: "/what-we-buy",
  HOW_IT_WORKS: "/how-it-works",
  AVAILABLE_WITH_US: "/available-with-us",
  CONTACT: "/contact",
  BLOGS: "/blogs",
  ADMIN_LOGIN: "/admin/login",
  ADMIN_DASHBOARD: "/admin",
  ADMIN_REGISTER: "/admin/register",
  ADMIN_DONATIONS: "/admin/queries",
  ADMIN_PRODUCTS: "/admin/products",
  ADMIN_ORGANIZATIONS: "/admin/organizations",
  ORGANIZATION_PROFILE: "/admin/organization-profile/:id",
  ADMIN_CATEGORIES: "/admin/categories",
  ADMIN_STATS: "/admin/stats",
  ADMIN_BLOGS: "/admin/blogs",
  NO_MATCH: "*",
} as const;
