import Step1 from "@rsces/assets/images/step1.jpg";
import Step2 from "@rsces/assets/images/step2.jpg";
import Step3 from "@rsces/assets/images/step3.jpg";
import Step4 from "@rsces/assets/images/step4.png";
import Step5 from "@rsces/assets/images/step5.jpg";
import Step6 from "@rsces/assets/images/step6.jpg";
import Step7 from "@rsces/assets/images/step7.png";
import { NAVIGATION_ROUTES } from "./routes/routes.constant";

// NAVBAR
export const NAVBAR_LINKS = [
  // { title: "Home", to: NAVIGATION_ROUTES.BASE },
  { title: "What we buy", to: NAVIGATION_ROUTES.WHAT_WE_BUY },
  { title: "How it works", to: NAVIGATION_ROUTES.HOW_IT_WORKS },
  { title: "What we sell", to: NAVIGATION_ROUTES.AVAILABLE_WITH_US },
  { title: "About Us", to: NAVIGATION_ROUTES.ABOUT_US },
  { title: "Blogs", to: NAVIGATION_ROUTES.BLOGS },
  { title: "Contact", to: NAVIGATION_ROUTES.CONTACT },
];

// FOOTER
export const FOOTER_LINKS = [
  { title: "About Company", to: NAVIGATION_ROUTES.ABOUT_US },
  { title: "What we buy", to: NAVIGATION_ROUTES.WHAT_WE_BUY },
  { title: "How it works", to: NAVIGATION_ROUTES.HOW_IT_WORKS },
  { title: "What we sell", to: NAVIGATION_ROUTES.AVAILABLE_WITH_US },
  { title: "Contact us", to: NAVIGATION_ROUTES.CONTACT },
];

export const HOW_IT_WORKS_STEPS = [
  {
    image: Step1,
    title: "Purchase and Collection of Recyclable and Reusable Waste",
    description:
      "Phohor Mohor's procurement and collection process begins with a consultation and assessment to identify the types of recyclable and reusable waste generated by clients and determine logistics for collection and transportation. This is followed by an initial assessment to review the type, quantity, and quality of the waste. Based on this assessment, a proposal is developed, including details such as price, quantity, and logistics. After negotiating and finalizing the terms with the client, regular pick-ups are arranged, and appropriate collection containers are provided to facilitate the segregation of waste.",
  },
  {
    image: Step2,
    title: "Transport to Facility",
    description:
      "Once the agreement is finalized and collection containers are provided, Phohor Mohor arranges regular pick-ups based on the client's requirements. The collected waste is then transported to their facilities for processing. This transportation process is managed to ensure efficiency and environmental responsibility.",
  },
  {
    image: Step3,
    title: "Segregate at Facility",
    description:
      "Upon arrival at the facility, the collected waste is segregated into different categories to streamline the processing. This segregation ensures that each type of waste is handled appropriately, enhancing the efficiency of the subsequent recycling and reuse processes.",
  },
  {
    image: Step4,
    title: "Repair and Maintenance of Reusable Items (For Sale)",
    description:
      "Reusable items collected from clients are repaired and maintained at Phohor Mohor's facility to ensure they meet quality standards. These refurbished items are then prepared for sale, extending their lifecycle and reducing waste.",
  },
  {
    image: Step5,
    title:
      "Sale of Recyclable Items at Recycling Center (Plastics Recycled at Own Facility)",
    description:
      "Recyclable materials, except plastics, are sorted and sold to other recycling centers. Phohor Mohor ensures these materials are processed in an environmentally responsible manner and used as raw materials by manufacturers and other customers.",
  },
  {
    image: Step6,
    title: "Recycle at Own Facility (Plastics)",
    description:
      "Plastics are processed at Phohor Mohor’s own recycling facility using advanced technologies to ensure environmentally responsible recycling. This minimizes waste and reduces the company’s carbon footprint. Other recyclable materials are sold to external recycling centers.",
  },
  {
    image: Step7,
    title: "Final Production for Sale",
    description:
      "The recycled and processed materials are transformed into final products ready for sale. These products are then marketed and sold to manufacturers and other customers, contributing to the circular economy and promoting sustainability by ensuring that recyclable and reusable waste is efficiently repurposed.",
  },
];

import ConsultingIcon from "@rsces/assets/icons/consultation.png";
import RecyclingIcon from "@rsces/assets/icons/recycle.png";
import WasteCollectionIcon from "@rsces/assets/icons/waste-collection.png";
import WasteSortingIcon from "@rsces/assets/icons/waste-sorting.png";

export const SERVICES = [
  {
    icon: WasteCollectionIcon,
    title: "Waste Collection",
    description:
      "Efficiently collecting recyclable and reusable waste from various sources using specialized equipment.",
  },
  {
    icon: WasteSortingIcon,
    title: "Waste Sorting",
    description:
      "We sort waste into categories like plastic, paper, metal, and glass to aid recycling and reduce landfill waste.",
  },
  {
    icon: RecyclingIcon,
    title: "Recycling",
    description:
      "We recycle plastic and collaborate to sustainably process other waste.",
  },
  {
    icon: ConsultingIcon,
    title: "Consulting",
    description:
      "We offer consulting services to businesses on reducing waste and implementing sustainable waste management practices.",
  },
];

export const MISSIONS = [
  {
    id: 1,
    label: "Promote sustainable development by reducing landfill waste.",
  },
  {
    id: 2,
    label: "Contribute to a cleaner and greener environment.",
  },
  {
    id: 3,
    label: "Raise awareness about the importance of waste management.",
  },
  {
    id: 4,
    label: "Encourage the adoption of sustainable waste management practices.",
  },
];

export const VISIONS = [
  {
    id: 1,
    label: "Become a leading waste management company in Nepal.",
  },
  {
    id: 2,
    label: "Promote sustainable development.",
  },
  {
    id: 3,
    label: "Contribute towards a healthier environment.",
  },
  {
    id: 4,
    label: "Expand services across the country.",
  },
  {
    id: 5,
    label: "Establish as a trusted partner for waste management.",
  },
];
